### ISSUE TITLE
Error when fire/water alarms are raised

### ISSUE THREAD

**Issue by ZishuoYang** [umd-lhcb/NeoBurnIn#8]
As previously mentioned, when fire and water alarms are raised successfully, CtrlClient.py gives error and crashes. I just tested and saw that the latest update did not fix this bug. 

The error message is `NeoBurnIn.io.client send(): 172 Transmission for the following msg failed, with the following exception TypeError: DataPassthru(date=<...>, name='WATER', value=None)`

**Comment by yipengsun** [comment]
The lines that generate that error are:

https://github.com/umd-lhcb/NeoBurnIn/blob/a67e245639c77c1cb45bf4cb7b8864353b812a49/NeoBurnIn/io/client.py#L169-L173

Previously, I thought the error was due to the Fire/Water alarm messages are ill-formed: In the `value` field, the alarm messages are either `WATER` or `FIRE`, but the `DataServer` is expecting a float, so the server would complain and the transmission would fail.

However, the actual error is an `Exception`, so there's some internal error that I'm missing.

**Comment by yipengsun** [comment]
@ZishuoYang I've temporarily made the error message more verbose, can you test again and post the error stack?

**Comment by ZishuoYang** [comment]
ok

**Comment by ZishuoYang** [comment]
No easy way to copy the text. I attach the screenshot here.

https://user-images.githubusercontent.com/12600353/84934808-d782fe00-b0a5-11ea-8f5a-6b706581fca1.png

**Comment by yipengsun** [comment]
OK, supposedly the exception caused by `valueGt` is fixed. Please test again.

**Comment by ZishuoYang** [comment]
Now I don't see any alarm raised in the DataServer.log, and the Maraton is not shut off. And the curl command to turn off the Maraton takes much longer (~1 minute vs a few seconds). 

I don't see any error prompt either.

**Comment by yipengsun** [comment]
The DataServer will not receive alarms. So that's expected. The problem then is the Maraton shut off.

**Comment by ZishuoYang** [comment]
But the alarms should be logged somewhere, right? Previously, we had the ability to tail some log and monitor the status.

**Comment by yipengsun** [comment]
I've updated the code again on the pi. Now:

1. The alarms will be printed out on screen, as well as logged in `logs/test_temp_ctrl_client.log`
2. The PSU operations are always logged in `logs/CtrlServer.log`

**Comment by yipengsun** [comment]
As of why turning of the Maraton single channel was much slower: We didn't enable the `minTimeOut` option, and the fire alarm was triggered multiple times; each time the pi tries to shut off **ALL** channels.

Basically, we were DDoS attacking the Maraton, making it **MUCH LESS** responsive. That's why turning off single channel was much slower afterwards.

Now, this doesn't explain why the Maraton was not turned off with alarm.

**Comment by yipengsun** [comment]
Another suggestion to debug why the Maraton was not turned off completely:

From the log file, I see that you tried to turn on Maraton channel 4. Replace `4` with `all` and try to turn off **ALL** channels manually.

If this doesn't work, try to reboot the Maraton control card.

**Comment by yipengsun** [comment]
My previous editing on the CtrlServer configuration was non-effective. I've corrected that and you can test again.

**Comment by ZishuoYang** [comment]
> Another suggestion to debug why the Maraton was not turned off completely:
> 
> From the log file, I see that you tried to turn on Maraton channel 4. Replace `4` with `all` and try to turn off **ALL** channels manually.
> 
> If this doesn't work, try to reboot the Maraton control card.

I turned on all channels by replacing channel number with 'all'. But, when trying to turn OFF all channels the same way, the terminal returned "success" while all channels stayed on. I had to turn off channels one by one.

**Comment by yipengsun** [comment]
But you were able to turn off channels one-by-one with the `curl` interface right? Then that's weird, because turning off all channels is just a loop where channels are turned off one-by-one:
https://github.com/umd-lhcb/NeoBurnIn/blob/2e8d0a98fc0a943bf2debb0b99a12fe26ce1b878/NeoBurnIn/io/server.py#L317-L323

**Comment by yipengsun** [comment]
Ah! I spotted the bug, it should be `psu.PowerOffCh(c)`!

**Comment by yipengsun** [comment]
You can test again, first manually, then try triggering the alarm.

**Comment by ZishuoYang** [comment]
@yipengsun OK, now the curl command to turn all channels off works. But triggering the alarm did not turn off maraton. After the msg "Fire alarm triggered", I get the following error:

`NeoBurnIn.io.server handler_psu_ctrl(): 304 Operation denied for changing PSU channel all to state off`

Repeating the test, I waited for 40s (minTimeOut) after turning on a channel, then triggered fire alarm, and saw the maraton channel turn off.  So the shutoff function works, but was again followed by multiple error prompts above due to the timeout limit. 

So some kind of timeout limit is necessary, not optional as you said before. But 40s is too long for testing and manual control. What is the lower limit you suggest while avoiding DDos? Instead of blocking triggers like this, what about adding a wait time in the send() function to slow down the alarm trigger itself?

**Comment by yipengsun** [comment]
I think when we trigger the fire/water alarm, it is inevitable that multiple alarms will be received by pi, even if we trigger it only once physically. That's why the `minTimeOut` is necessary.

I think `minTimeOut = 40` is fine for automatic controls: We don't expect to have frequent operations when controlling automatically.

For the manual control, maybe I should just create another server entry that doesn't have any timeout.

**Comment by ZishuoYang** [comment]
@yipengsun What about adding a wait time to slow down the alarm itself? I'll be more specific:


```
    def run(self):
        while not self.stop_event.wait(self.interval):
            if self.read_channel() == 0:
                self.alarm()
                time.sleep(30) # Add this to wait for 30s before reading alarm GPIO again 

```
(FireAlarm.py)

**Comment by yipengsun** [comment]
I don't think this works. The reason is: What you quoted is the fire alarm detection code, and notice that the `while` loop has a `self.interval` argument.

This means that for every `self.interval` (say, 1 second), we detect if fire alarm is triggered. If we put additional `time.sleep` inside, then the fire alarm becomes much less responsive (i.e. the total sleep time between two detections will be `self.interval + 30`).

**Comment by yipengsun** [comment]
Actually, what I said was wrong. The sleep is only triggered if alarm is detected, so this could work for both fire and water alarm.

Still, we need a timeout for the thermal cycling: For a few seconds, the temperature will be below/above threshold temperatures, and we don't want to repeatedly open/close the valve.

So I think we can just provide another manual interaction entry that doesn't have timeout. But for the automatic control, we should have a relatively large timeout (~60-120 s) so we don't repeatedly operating on anything.

**Comment by ZishuoYang** [comment]
Yeah, my idea is to slow down the alarm only **after** the first alarm trigger. After the first fire detection, I don't see why we need to keep checking every second.

**Comment by yipengsun** [comment]
I'd like to hear @CoffeeIntoScience @manuelfs opinion on how to proceed:

We discovered that when fire/water alarm is physically triggered once, they actually produce multiple alarm messages.

This means that Maraton will receive lots of shut down channel commands in a short period of time (like a DDoS attack to Maraton). To prevent this, we have two solutions:

1. Have a timeout on the Maraton operation (basically require two operations must be N seconds apart, and the controller will refuse all operations before the timeout)

2. Block the generation of alarm for a period of seconds when the alarm is triggered


I've received lots of complaints regarding the timeout, since that makes manual control a PITA. So I think at least I'll implement point 2 (@ZishuoYang's idea).

The remaining question is: should we keep the timeout? I think timeout is still useful for the relay control (we don't want to block the readout of the thermistor, ever).

In addition, I can implement another set of manual control entries that doesn't have timeout. So the timeout will only apply to the automatic system.

**Comment by manuelfs** [comment]
I'll defer to @ZishuoYang and @CoffeeIntoScience who are actually using the system, but I think option 2 (*debouncing* the alarm) is definitely needed, as one does not want to have spurious repeated alarms. The same thing is done when you press a button: there's is some bouncing that needs to be suppressed.

**Comment by yipengsun** [comment]
I've implemented deboucing for the alarms. I noticed that the temp threshold for turning on/off alarms have changed. @ZishuoYang Do you want to keep your change or revert to previous default? 

Otherwise I can't merge my updates to the pi.

**Comment by ZishuoYang** [comment]
@yipengsun You can revert it. I used it for testing but forgot to change it back.
