### ISSUE TITLE
CtrlClient.py error: cannot find file under w1/device/

### ISSUE THREAD

**Issue by ZishuoYang** [umd-lhcb/NeoBurnIn#9]
When running CtrlClient.py, I get the following error:

```
No such file or directory: '/sys/bus/w1/devices/28-0000098d8197/w1_slave'
```

**Comment by yipengsun** [comment]
I think this is because that particular thermal sensor is somehow disconnected from the pi.

**Comment by ZishuoYang** [comment]
It's not this particular sensor. I removed its filepath from test_temp_ctrl_client.yml, but the error remains (with the next sensor). 

And all physical connections look fine.

**Comment by yipengsun** [comment]
I just did a `ls /sys/bus/w1/devices` and the only result is:
```
w1_bus_master1
```

So, pi doesn't recognize any w1 device. Indeed let's try reboot first. If still nothing shows up, then it is very likely that some connection is messed up.

The reason is: The pi system is not updated and has identical configuration as pre-shutdown. And w1 device discovery is a kernel-only function.

Still, just to be sure, let me re-configure the pi with our current setting and packages (This is **NOT** an update) to ensure the software is what it supposed to be, and let's reboot and test again.

**Comment by ZishuoYang** [comment]
After checking that there were no loose connections, I unplugged and plugged the connectors back anyway. This turned out to fix the problem somehow. I will document this in https://github.com/umd-lhcb/ut-hw-doc/blob/master/docs/burnin/burnin_doc.md
